version: '3'

services:

  app:
    build: .
    container_name: iniciando-nestjs-app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    image: mysql:5.7
    container_name: iniciando-nestjs-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - iniciando-nestjs-dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=iniciando_nestjs
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root

volumes:
  iniciando-nestjs-dbdata:
    external: true
